- contracts/Gauge.sol
- contracts/GaugeFactory.sol
- contracts/VeYfiRewards.sol
- contracts/Voter.sol
- contracts/interfaces/IGauge.sol
- contracts/interfaces/IGaugeFactory.sol
- tests/functional/conftest.py
- tests/functional/test_gauge.py
- tests/functional/test_ve_yfi_rewards.py
- tests/functional/test_voter.py
Add sweep function in order to be able to sweep airdropped tokens
Fixes #4
> feat: add sweep

- contracts/Voter.sol
- contracts/VotingEscrow.vy
- contracts/interfaces/IVotingEscrow.sol
- tests/functional/test_voter.py
- tests/functional/test_voting_escrow.py
Add vote delegation 
Fixes #12
> feat: vote delegation

- contracts/Voter.sol
> feat: add events to vote

- contracts/Voter.sol
- tests/functional/test_voter.py
> feat: remove vault from rewards

- contracts/Gauge.sol
- contracts/VeYfiRewards.sol
- contracts/VotingEscrow.vy
- contracts/interfaces/IVotingEscrow.sol
- tests/functional/test_gauge_reward_distribution.py
- tests/functional/test_ve_yfi.py
- tests/functional/test_voting_escrow.py
Add mechanism for governance to unlock all tokens from this contract making this contract useless.
> feat: unlock for all mechanism

- contracts/Gauge.sol
- tests/functional/test_gauge.py
- tests/functional/test_gauge_reward_distribution.py
Added tests for Gauge.sol. Left out a small amount of tests since I am still unfamiliar with the calculations for rewards but will do them in a separate PR later once I am more familiar with them.
Fixes #10
> test: added Gauge.sol tests

- contracts/ExtraReward.sol
- contracts/Gauge.sol
- contracts/VeYfiRewards.sol
> chore: fix typos in docs + code

- contracts/ExtraReward.sol
- contracts/VeYfiRewards.sol
Use consistent naming for function arguments.
> fix: naming

- contracts/Voter.sol
> feat: max number of delegation a user can get

- contracts/Gauge.sol
> feat: prevent rewards to be distributed forever

- contracts/Gauge.sol
> fix: gauge make sure addresses are not zero

- contracts/Gauge.sol
> fix: possible overflow fixes#41

- contracts/VotingEscrow.vy
In order to ease creating of vesting/locks for the doers, add a function that let multisig create a lock for someone.
> feat: ease lock creation for vesting

- contracts/BaseGauge.sol
- contracts/Gauge.sol
- contracts/Voter.sol
- tests/functional/test_extra_rewards.py
- tests/functional/test_gauge.py
- tests/functional/test_ve_yfi_rewards.py
- tests/functional/test_voter.py
> chore: change revert messages

- contracts/Gauge.sol
- contracts/GaugeFactory.sol
> Add event to gauge initialize

- contracts/Gauge.sol
> chore: add deleted rewards on clearExtraRewards

- contracts/BaseGauge.sol
- contracts/ExtraReward.sol
- contracts/Gauge.sol
- contracts/VeYfiRewards.sol
> chore: add event to updateReward

- contracts/VotingEscrow.vy
> chore: add event to unlock

- contracts/BaseGauge.sol
> chore: add event to sweep

- contracts/BaseGauge.sol
- tests/functional/test_gauge_reward_distribution.py
> chore: add event to _notifyRewardAmount

- contracts/VotingEscrow.vy
> chore: add event to ve init

- contracts/Registry.sol
> chore: use enumerable set

- contracts/Gauge.sol
- contracts/VeYfiRewards.sol
- contracts/VotingEscrow.vy
- contracts/interfaces/IVotingEscrow.sol
- contracts/test/NextVe.sol
- tests/functional/test_gauge_reward_distribution.py
- tests/functional/test_voting_escrow.py
With the migration mechanism we don't need the unlock mechanism.
> Remove unlock mechanism

- contracts/VotingEscrow.vy
- contracts/interfaces/IVotingEscrow.sol
- contracts/test/NextVe.sol
- tests/functional/test_voting_escrow.py
Add a function to migrate funds to a new ve contract.
The receiving contract will have to take care of creating a new lock, it can fetch lock information on the existing ve contract.
> feat: add migration to ve

- contracts/Gauge.sol
- contracts/VeYfiRewards.sol
> chore: refactor deposits

- contracts/BaseGauge.sol
- contracts/ExtraReward.sol
- contracts/Gauge.sol
- contracts/GaugeFactory.sol
- contracts/Registry.sol
- contracts/VoteDelegation.sol
- contracts/VotingEscrow.vy
> chore: add indexed to events

- contracts/BaseGauge.sol
fix: make sure owner isn't zero
> fix: make sure owner isn't zero

- contracts/Gauge.sol
All log to transferQueuedPenalty
> feat: add log to transferQueuedPenalty

- contracts/ExtraReward.sol
> fix: make sure _gauge isn't zero

- contracts/ExtraReward.sol
- contracts/Registry.sol
fix: registry add missing zero checks
> fix: registry add missing zero checks

- contracts/ExtraReward.sol
- contracts/Gauge.sol
make sure _rewardManager isn't zero
> feat: make sure _rewardManager isn't zero

- contracts/Gauge.sol
> fix: _getReward

- contracts/Gauge.sol
> docs: _getReward

- contracts/BaseGauge.sol
Voting shouldn't be every week.
> chore: bump reward distribution duration

- contracts/Registry.sol
- tests/functional/test_extra_rewards.py
- tests/functional/test_gauge.py
- tests/functional/test_gauge_reward_distribution.py
- tests/functional/test_ve_yfi_rewards.py
> chore: add back immutable

- contracts/VotingEscrow.vy
- tests/functional/conftest.py
It seems like the Aragon compatibility isn't needed, better remove this and save some gas.
> chore: remove aragon compatibility

- requirements.txt
- tests/functional/test_voting_escrow.py
Removed a hack due to a bug in Ape <0.1.4
> fix: no longer need weird slicing in Ape 0.1.4+

- contracts/VotingEscrow.vy
> fix: remove unused SmartWalletChecker code

- contracts/BaseGauge.sol
- contracts/ExtraReward.sol
- contracts/Gauge.sol
Make sure extra rewards aren't duplicates.
> feat: make sure extra rewards aren't duplicates

- contracts/ExtraReward.sol
- contracts/Gauge.sol
- tests/functional/test_extra_rewards.py
- tests/functional/test_gauge_reward_distribution.py
> feat: snapshot boost at deposit & update boost to 10x & send non boosted to veYFI & remove boost on extra rewards.

- .solhint.json
- contracts/BaseGauge.sol
- contracts/ExtraReward.sol
- contracts/Gauge.sol
- contracts/GaugeFactory.sol
- contracts/Registry.sol
- contracts/VotingEscrow.vy
- contracts/interfaces/IBaseGauge.sol
- contracts/interfaces/IExtraReward.sol
- contracts/interfaces/IGauge.sol
- contracts/interfaces/IVotingEscrow.sol
- contracts/test/Token.sol
- package.json
- tests/functional/test_gauge_reward_distribution.py
- yarn.lock
> feat: add kick & approve deposit claim lock

- requirements.txt
> chore: bump ape version

- ape-config.yaml
- scripts/deploy.py
> feat: test deploy script

- ape-config.yaml
- scripts/deploy.py
> Add test deploy script

- contracts/Gauge.sol
This PR adds some natspec definitions to help reviewers understand the assumptions/business logic of the gauge.
> Add some natspec to Gauge

- ape-config.yaml
- contracts/BaseGauge.sol
- contracts/Gauge.sol
- contracts/interfaces/IERC4626.sol
- contracts/interfaces/IGauge.sol
- tests/functional/test_gauge.py
- tests/functional/test_gauge_reward_distribution.py
- tests/functional/zap_test.py
Make Gauge IERC4626 compliant.
> try out IERC4626

- contracts/RewardPool.vy
fix some changes not appearing caused by a mistake during merge
> fix: wrong merge

- ape-config.yaml
- contracts/RewardPool.vy
- contracts/VotingYFI.vy
- developing.md
- tests/conftest.py
- fix not setting a reward pool
- use interfaces instead of casting
> fix: veyfi

- contracts/Gauge.sol
> chore: format

- .github/workflows/test.yaml
- ape-config.yaml
- requirements.txt
> chore: bump versions

- README.md
Small update on readme to fix incomplete setup instructions
> fix: readme setup instructions

- contracts/RewardPool.vy
- tests/functional/test_extra_rewards.py
> fix: reward pool Calculates Incorrect Balances

- contracts/RewardPool.vy
> fix: function _find_timestamp_epoch() can be view

- contracts/RewardPool.vy
> docs: fix comment

- contracts/RewardPool.vy
> fix: increase checkpoint to 40 weeks

- contracts/VotingYFI.vy
Small corrections to natspec to clarify documentation 
Fixes # [(chain security audit issue 5.9)](https://github.com/yearn/veYFI/issues/176)
Clarifies [(chain security audit issue  5.10)](https://github.com/yearn/veYFI/issues/176)
> fix: small natspec corrections

- contracts/RewardPool.vy
Small gas optimization to exit early in `checkpoint_token` method to address audit issue
Expected regression tests should work, optimization keeps final state the same without using the loop
- Fixes # [(statemind audit issue I10)](https://github.com/yearn/veYFI/issues/175)
> fix: small gas optimization in checkpoint_token method

- tests/conftest.py
- tests/functional/test_voting_escrow.py
The tests ran inconsistently without test running at the beginning of the week.
> test: fix inconsistency
